<a href="https://colab.research.google.com/github/Sonchecho/DataScience300/blob/main/Ejercicios_semana_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
import os
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [5]:
%cd '/content/gdrive/MyDrive/Bootcamp semana 1 python /Bootcamp semana 1 python /Semana 1 PYTHON '

/content/gdrive/MyDrive/Bootcamp semana 1 python /Bootcamp semana 1 python /Semana 1 PYTHON 


## Ejericicio 1
Creen un vector a entre 5 y 6 con intervalo de 0.2 y guardenlo en formato ```datos.npy``` y luego carguenlo con nombre b y muestrelo

In [10]:
import numpy as np  
a=np.arange(5,6,0.2)
print(a)
a.tofile('datos.npy')
b=np.fromfile('datos.npy')
b

[5.  5.2 5.4 5.6 5.8]


array([5. , 5.2, 5.4, 5.6, 5.8])

## Ejercicio 2

Cree un una matriz A con ```np.array```

$$\begin{bmatrix} 
	1 & 3 & 5 \\
	11 & 9 & 7\\
	13 & 15 & 17 \\
	\end{bmatrix}$$

Luego de eso utilize el metodo ```np.sort``` con  el argumento ```axis =1``` or ```axis=0```

A que conclusiones llegan? 

In [13]:
A= np.array([[2,5,4],[8,9,1],[7,4,3]])
print(A)
print(np.sort(A,axis=1))
B=np.sort(A,axis=1)
print(B)

C=np.sort(A,axis=0)

print(C)


[[2 5 4]
 [8 9 1]
 [7 4 3]]
[[2 4 5]
 [1 8 9]
 [3 4 7]]
[[2 4 5]
 [1 8 9]
 [3 4 7]]
[[2 4 1]
 [7 5 3]
 [8 9 4]]


## Ejercicio 3

Cree una matriz de 3x3 B, como la siguiente:

$$\begin{bmatrix} 
	9 & 1 & 2 \\
	1 & 9 & 5\\
	2 & 5 & 9 \\
	\end{bmatrix}$$

1. Convierta la matriz a un vector de 1x9
2. Ordene de de menor a mayor el vector
3. Aplique un filtro para extraer solo los numeros menores que 9

In [62]:
B=np.array([[1,3,2],[7,8,9],[5,6,4]])
print(B)
print('punto 1')

x=B.reshape(1,9)
print(x)

print('punto 2')

p=np.sort(x,axis=1)
print(p)
print(np.sort(x,axis=1))

print('punto 3')

condi=np.where(p<9,1,0)
print(np.extract(condi,p))





[[1 3 2]
 [7 8 9]
 [5 6 4]]
punto 1
[[1 3 2 7 8 9 5 6 4]]
punto 2
[[1 2 3 4 5 6 7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
punto 3
[1 2 3 4 5 6 7 8]
[0 1 2 3 4]
